Enable multiple bots
haesleinhuepf/bia-tischi pull request #10
Opened 2023-09-23 10:02 UTC by tischi

Hi,

Sitting at FRA on my way to the course in Bangalore, I started refactoring.

I did not run the code yet, but maybe you can already have a look.

Question: do you know whether one can somehow launch/test the code from within pyCharm?

2023-09-24 16:11 UTC, tischi commented
@haesleinhuepf 

I do not understand what these lines of code in `__init__.py` are doing:

```
from ._machinery import bob, init_assistant

bob.initialize = init_assistant
bob.__version__ = __version__
```

`bob` is a function, right? 

......I just asked chatGPT and got the answer....mind-blowing for a Java dude like me.... :-)

2023-09-24 16:36 UTC, tischi commented
I fixed couple of bugs, but somehow the splitting of the text and code does not seem to work.

@haesleinhuepf is there a way to lauch the notebook such that I am in debug mode in pycharm so that I can inspect variables at breakpoints?

2023-09-24 19:34 UTC, tischi commented
@haesleinhuepf 

There are now `bob` and `xbob`, the latter executing immediately.

For `xbob` I get an error in the demo notebook that the variable `a` is not defined. I think that probably the `_context.variables` need to be updated again whenever `xbob` is asked a question?! Maybe I accidentally deleted something here. Could you maybe have a quick look?

2023-09-29 12:33 UTC, tischi commented
[746b577](https://github.com/haesleinhuepf/bia-tischi/pull/10/commits/746b577f64c8013a3e19b6219d38ad95dcdaefcf) fixes the issue with the jupyter notebook variables not being visible within the code.

2023-10-04 13:36 UTC, haesleinhuepf requested changes
Hi @tischi ,

fantastic, thanks for working on this. Especially adding the code to the next cell is a super amazing feature!

I'm just testing your proposed changes and it works great! I put some comments below, mostly related to code-quality.  Long-term, in general, I like concise PRs where only one thing is changed. It would be much easier to review  and discuss then.

* I like this warning, but it might not need to be so "loud":
![image](https://github.com/haesleinhuepf/bia-tischi/assets/12660498/4dd252a0-4570-4d37-a156-a539177bf89e)
I would remove the entire block (incldugin "Additional information". Users will get used to this without notifying them every individual time,

More comments below.

Best,
Robert

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/__init__.py
> +from ._machinery import ai, init_assistant
We should not call it `ai` as others have done that already: https://github.com/jupyterlab/jupyter-ai
I created an issue to discuss naming: https://github.com/haesleinhuepf/bia-tischi/issues/20

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_machinery.py
> +        return cls.output_price[index]
I would keep the pricing out for now and discuss it in a later pull-request separately if possible.

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_machinery.py
> +#     output_text(result)
We should remove this before merging.

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_machinery.py
> +#     output_text(result)
We should also clean this up before merging

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_machinery.py
> +    Context.variables = get_ipython().user_ns
Awesome, I'm learning something here! Thanks!

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_machinery.py
> +    #     return "Code was generated and executed."
Remove this before merging

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_machinery.py
> +            get_ipython().set_next_input(code, replace=False)
OMG. I'm loving this so much!

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_machinery.py
> +    print("Assistant initialised.\n\nYou can call it using the %ai command, e.g.\n\n%ai please generate a random 2D "
Potentially replace the name `ai` here again with `bob`.

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_utilities.py
I agree with the changes here. It would have been better in a separate PR with a title such as `improve code quality`

2023-10-04 13:36 UTC, haesleinhuepf commented on src/bia_tischi/_utilities.py
> +    text = details + text
What does this do?

2023-10-04 13:37 UTC, haesleinhuepf commented on src/bia_tischi/_utilities.py
> +    text = details + text
I presume it's related to pricing and vote for removing it for now.

2023-10-04 13:44 UTC, haesleinhuepf commented
One more request: This doesn't work anymore:
```
from bia_tischi import ai
```
```
%%ai
please write code to load blobs.tif and visualize it
```
Error:
```
'Please first init the assistant!'
```
It would be great if the assistant would be initialized with default parameters when used the first time. See here: 
https://github.com/haesleinhuepf/bia-tischi/blob/771c638a7bd8d8430dc5d9e0167e08b8c24e02f4/src/bia_tischi/_machinery.py#L12

2023-10-05 07:53 UTC, closed without merging